######PIPELINE OPTIONS#######
# This first set of parameters is meant to be used to select the pipeline execution mode
# Options are:
# - BATCH
# - JOINT_CALL
#
# BATCH mode is meant to be used to run the pipeline splitting the samples in different batches from
# alignment to HaplotypeCaller 
#
# JOINT_CALL mode is meant to be the subsequent step, where we collect all gVCF and perform 
# - joint variant calling
# - VQSR filtering
# - variant annotation
#
#
##############################
pipe_mode : "BATCH" #change to "JOINT_CALL" to work in joint call mode.

#Parameter file for fastq preprocesing step
samples: "VARCALL_SAMPLE_FILE_PATH"

#prject name
proj_name : "WGS_VarCalling"

#define some variables to be used for some rules
#library name
lb : "L001"
pl : "Illumina"
#compression level
cl : 5

ip1 : 500         #interval_padding (bp)  # HaplotypeCaller
maa : 3           #max alternate alleles  # HaplotypeCaller

#java options
java_opts:
  opt_all: '-XX:ParallelGCThreads=1'       # All GATK steps
  opt1x: '-Xms5g -Xmx5g -XX:+UseSerialGC' #memoria java       # Chr12,Wg12,21x2
  opt2x: '-Xms10g -Xmx10g -XX:+UseSerialGC'    #java options       # 02,03,04,05x2,06,07,08,09,Chr10,Wg10x3,14,15,17,18,23,24,Chr25,Chr26
  opt3x: '-Xms25g -Xmx25g -XX:+UseSerialGC'    #memoria java       # 19
  opt4x: '-Xms100g -Xmx100g -XX:+UseSerialGC'   #memoria java       # 20

#################################################################################
#paths and subfolders containing data we need for the pipeline to run
references:
  # basepath: "/home/max/Work/OTHER_PJS/HQ_WGS_QC/pipeline_tests/test_files/resources"
  basepath: "/storage/burlo/cocca/resources"
  provider: "hgRef"
  release: "GRCh38.p13"

genome_fasta: "GCA_000001405.15_GRCh38_full_plus_hs38d1_analysis_set.fna"
callable_intervals: "wgs_intervals"
#################################################################################

call_chr: ["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22","chrX_PAR","chrX_NONPAR","chrY"]

known_variants:
  dbsnp_latest: "/storage/burlo/cocca/resources/dbSNP/human_9606_b154_GRCh38p12/GCF_000001405.38.vcf.gz"
  dbsnp: "/storage/burlo/cocca/resources/gatk4hg38db/dbsnp_151.hg38.vcf.gz"
  hapmap: "/storage/burlo/cocca/resources/gatk4hg38db/hapmap_3.3.hg38.vcf.gz"
  g1k: "/storage/burlo/cocca/resources/gatk4hg38db/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  omni: "/storage/burlo/cocca/resources/gatk4hg38db/1000G_omni2.5.hg38.vcf.gz"
  mills: "/storage/burlo/cocca/resources/gatk4hg38db/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  indels: "/storage/burlo/cocca/resources/gatk4hg38db/Homo_sapiens_assembly38.known_indels.vcf.gz"
  axiom: "/storage/burlo/cocca/resources/gatk4hg38db/Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"

############################################
#Template to pre-process fastq files
# with parameters for different tools in different rules
rules:
  ubam_gen:
    out_dir: "1.ALIGNMENT"
  bwa_mem:
    out_dir: "1.ALIGNMENT"
    threads: 12
    mem: 60000
  map_unmap_merge:
    out_dir: "1.ALIGNMENT"
  mark_dup:
    out_dir: "1.ALIGNMENT"
    threads: 8
    mem: 10000
  sort_bam:
    out_dir: "1.ALIGNMENT"
    threads: 12
    mem: 10000
  bqsr_proc:
    out_dir: "2.BQSR"
  gather_bqsr:
    out_dir: "2.BQSR"
  apply_bqsr:
    out_dir: "2.BQSR"
  gatk_hap_caller:
    out_dir: "3.VarCall"
  stats:
    out_dir: "4.Stats"
    mem: 1000
  picard_WGSMetrics:
    arguments: "MINIMUM_MAPPING_QUALITY=-1 MINIMUM_BASE_QUALITY=-1 READ_LENGTH=150 COUNT_UNPAIRED=true"
  #if running in BATCH mode, all the following paths will not be used, so, no need to specify
  split_intervals:
    scatter_count: 25
    out_dir: "5.SplittedIntervals"
  gatk_genomics_db_import:
    #This parameter is used to trigger the creation of a new db_import or to append data to existing resources. To add data to an existing db, change the parameter to --genomicsdb-update-workspace-path
    genomics_db_option: "--genomicsdb-workspace-path" #default: --genomicsdb-workspace-path. Allowed: --genomicsdb-workspace-path/--genomicsdb-update-workspace-path
    arguments: "--genomicsdb-shared-posixfs-optimizations true --batch-size 100"
    out_dir: "6.DbImport"
  gatk_genotype_gvcfs:
    temp_folder: "/local_scratch/burlo/cocca/localtemp"
    arguments: "--genomicsdb-shared-posixfs-optimizations -G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation --include-non-variant-sites --only-output-calls-starting-in-intervals"
    out_dir: "7.GenotypeGVCFs"
  pre_vqsr_rules:
    out_dir: "8.VQSR_input"
  gatk_variant_recalibrator:
    SNP:
      tranches: "-tranche 100.0 -tranche 99.99 -tranche 99.98 -tranche 99.97 -tranche 99.96 -tranche 99.95 -tranche 99.94 -tranche 99.93 -tranche 99.92 -tranche 99.91 -tranche 99.9 -tranche 99.85 -tranche 99.8 -tranche 99.75 -tranche 99.7 -tranche 99.65 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0"
      annotations: "-an QD -an MQRankSum -an ReadPosRankSum -an FS -an MQ -an SOR -an DP"
      arguments: "-mode SNP --max-gaussians 6"
    INDEL:
      tranches: "-tranche 100.0 -tranche 99.99 -tranche 99.98 -tranche 99.97 -tranche 99.96 -tranche 99.95 -tranche 99.8 -tranche 99.7 -tranche 99.6 -tranche 99.5 -tranche 99.0 -tranche 97.0 -tranche 96.0 -tranche 95.0 -tranche 94.0 -tranche 93.5 -tranche 93.0 -tranche 92.0 -tranche 91.0 -tranche 90.0"
      annotations: "-an FS -an ReadPosRankSum -an MQRankSum -an QD -an SOR -an DP"
      arguments: "-mode INDEL --max-gaussians 4"
    out_dir: "9.VQSR"
    threads: 20
  gatk_apply_VQSR:
    SNP:
      arguments: "--truth-sensitivity-filter-level 99.99 --create-output-variant-index true"
    INDEL:
      arguments: "--truth-sensitivity-filter-level 95.0 --create-output-variant-index true"
    out_dir: "10.Apply_VQSR"
    threads: 5
  recal_pass_filter:
    out_dir: "10.Apply_VQSR"
  rsid_annotation:
    out_dir: "11.rsID_annotation"
  phase:
    genetic_map: "/large/___HOME___/burlo/cocca/software/eagle/Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz"
    out_dir: "12.phased"



#########SET UP YOUR EMAIL HERE ##############
mail: ""
#########SET UP YOUR EMAIL HERE ##############

### - GENERAL PATHS - ###
### - PATH FILE - ###
files_path:
  base_out: "VARCALL_OUT_FOLDER"
  tmp: "localtemp"
  log_dir: "Log"
  benchmark: "benchmarks"
  base_joint_call_path : "[...]" #this folder should be located in a different path, so that can be accessed by all concurrent batch instances of the pipeline, to create symlink to gvcf files. Than, it could be read in joint call mode and used to perform DbImport and all other steps


### - PATH TOOL - ###
ALIGN_TOOL: "bwa-mem2"
PHASE_TOOL: "eagle"
PICARD_TOOL: "picard"
SAMBAMBA_TOOL: "sambamba"
SAMTOOLS: "samtools"
BCFTOOLS: "bcftools"
GATK_TOOL: "gatk"
BEDTOOLS: "bedtools"
